version: '3'
services:
  backend:
    build:
        context: .
        dockerfile: ./Dockerfile
    restart: "no"
    volumes:
        - .:./app
    ports:
        - "8000:8000"
    volumes:
        - .:/code
    command: bash entry.sh
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prabin
      - POSTGRES_PASSWORD=prabin
      - POSTGRES_DB=project_db

volumes:
  postgres_data: